services:
  - type: web
    name: fashionstore-platform
    runtime: docker
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: SECRET_KEY
        generateValue: true
      - key: EMAIL_HOST_USER
        value: mrgrueso2005@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: plwx ztda stmt qxeu
      - key: DEFAULT_FROM_EMAIL
        value: SIGEPSI <mrgrueso2005@gmail.com>
      - key: STRIPE_SECRET_KEY
        value: sk_test_51UEsz81HD8WYieY54Eoz9aGdj05qbsEnEbLOISaxEf5TF2E6RWswKA3lsGO0Au0YVodJ0JOqbRElxv5GUlgwcYHY00LRGUdXFK
      - key: STRIPE_PUBLISHABLE_KEY
        value: pk_test_51UEsz81HD8WYieY5OVqcN7AqDcwmlIpf9ClUu7VzfdPDigt5FgbaTPuk8cErY6ySu3CXc8U0r7SY2UINr0e3AMyg00LCwwrfgN
      - key: STRIPE_CURRENCY
        value: bob
      # Si se vincula una base de datos PostgreSQL en Render, descomentar:
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: fashionstore-db
      #     property: connectionString

# (Opcional) Descomentar si se desea aprovisionar base de datos PostgreSQL gestionada en Render:
# databases:
#   - name: fashionstore-db
#     plan: free
#     region: oregon
#     databaseName: fashionstore_db
#     user: postgres

